import "../styles/globals.css";
import Header from '@/components/header.jsx'
import Footer from '@/components/footer.jsx'
import AOSProvider from '@/components/aosProvider'

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
    title: 'Gheals Tech – Digital Solutions',
    description: 'Digital agency delivering tech solutions',
    icons: {
      icon:'/img/favicon.ico'
    }
  }

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className='bg-[whitesmoke]'
      >
        <AOSProvider>
          <Header />
          {children}
          <Footer />
        </AOSProvider>
      </body>
    </html>
  );
}
